# Generated by Django 5.1 on 2024-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
