# Generated by Django 5.1 on 2024-10-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_producto_especificaciones_tecnicas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valido_hasta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
