# Generated by Django 5.1 on 2024-10-18 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_carrito_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetodoEnvio',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='session_key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
