# Generated by Django 5.1 on 2024-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_delete_codigopromocional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('es_valor_fijo', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
